version: "3"
services:
  predict_frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    tty: true
    volumes:
      - ./frontend:/app #マウントするフォルダ
    environment: #環境変数
      SHELL: "/bin/bash"
    ports:
      - "3000:3000"
    working_dir: /app
    command: bash -c "npm run dev"

  predict_backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    tty: true
    volumes:
      - ./backend:/app #マウントするフォルダ
    environment: #環境変数
      SHELL: "/bin/bash"
    ports:
      - "8000:8000"
    working_dir: /app
    command: bash -c "python manage.py runserver 0.0.0.0:8000"